// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type hTTPShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}

type rCONShadow struct {
	Host           *string `json:"host"           toml:"host"           yaml:"host"`
	Port           *int    `json:"port"           toml:"port"           yaml:"port"`
	Password       *string `json:"password"       toml:"password"       yaml:"password"`
	TimeoutSeconds *int    `json:"timeoutSeconds" toml:"timeoutSeconds" yaml:"timeoutSeconds"`
	MaxConcurrent  *int    `json:"maxConcurrent"  toml:"maxConcurrent"  yaml:"maxConcurrent"`
}

type mapShadow struct {
	Name        *string  `json:"name"        toml:"name"        yaml:"name"`
	ImagePath   *string  `json:"imagePath"   toml:"imagePath"   yaml:"imagePath"`
	HalfExtentX *float64 `json:"halfExtentX" toml:"halfExtentX" yaml:"halfExtentX"`
	HalfExtentY *float64 `json:"halfExtentY" toml:"halfExtentY" yaml:"halfExtentY"`
}

type pollerShadow struct {
	IntervalSeconds  *int  `json:"intervalSeconds"  toml:"intervalSeconds"  yaml:"intervalSeconds"`
	IdleAfterSeconds *int  `json:"idleAfterSeconds" toml:"idleAfterSeconds" yaml:"idleAfterSeconds"`
	Health           *bool `json:"health"           toml:"health"           yaml:"health"`
	HealthPerPoll    *int  `json:"healthPerPoll"    toml:"healthPerPoll"    yaml:"healthPerPoll"`
}

type configShadow struct {
	LogLevel *string       `json:"logLevel" toml:"logLevel" yaml:"logLevel"`
	HTTP     *hTTPShadow   `json:"http"     toml:"http"     yaml:"http"`
	RCON     *rCONShadow   `json:"rcon"     toml:"rcon"     yaml:"rcon"`
	Map      *mapShadow    `json:"map"      toml:"map"      yaml:"map"`
	Poller   *pollerShadow `json:"poller"   toml:"poller"   yaml:"poller"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("logLevel", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.RCON.Host = "127.0.0.1"
	set("rcon.host", configulator.LayerDefault, "default tag")
	cfg.RCON.Port = 7779
	set("rcon.port", configulator.LayerDefault, "default tag")
	cfg.RCON.TimeoutSeconds = 5
	set("rcon.timeoutSeconds", configulator.LayerDefault, "default tag")
	cfg.RCON.MaxConcurrent = 4
	set("rcon.maxConcurrent", configulator.LayerDefault, "default tag")
	cfg.Map.Name = "auto"
	set("map.name", configulator.LayerDefault, "default tag")
	cfg.Map.HalfExtentX = 0.0
	set("map.halfExtentX", configulator.LayerDefault, "default tag")
	cfg.Map.HalfExtentY = 0.0
	set("map.halfExtentY", configulator.LayerDefault, "default tag")
	cfg.Poller.IntervalSeconds = 10
	set("poller.intervalSeconds", configulator.LayerDefault, "default tag")
	cfg.Poller.IdleAfterSeconds = 30
	set("poller.idleAfterSeconds", configulator.LayerDefault, "default tag")
	cfg.Poller.Health = true
	set("poller.health", configulator.LayerDefault, "default tag")
	cfg.Poller.HealthPerPoll = 4
	set("poller.healthPerPoll", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("logLevel", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.RCON != nil {
		if s.RCON.Host != nil {
			cfg.RCON.Host = *s.RCON.Host
			set("rcon.host", configulator.LayerFile, file)
		}
		if s.RCON.Port != nil {
			cfg.RCON.Port = *s.RCON.Port
			set("rcon.port", configulator.LayerFile, file)
		}
		if s.RCON.Password != nil {
			cfg.RCON.Password = *s.RCON.Password
			set("rcon.password", configulator.LayerFile, file)
		}
		if s.RCON.TimeoutSeconds != nil {
			cfg.RCON.TimeoutSeconds = *s.RCON.TimeoutSeconds
			set("rcon.timeoutSeconds", configulator.LayerFile, file)
		}
		if s.RCON.MaxConcurrent != nil {
			cfg.RCON.MaxConcurrent = *s.RCON.MaxConcurrent
			set("rcon.maxConcurrent", configulator.LayerFile, file)
		}
	}
	if s.Map != nil {
		if s.Map.Name != nil {
			cfg.Map.Name = *s.Map.Name
			set("map.name", configulator.LayerFile, file)
		}
		if s.Map.ImagePath != nil {
			cfg.Map.ImagePath = *s.Map.ImagePath
			set("map.imagePath", configulator.LayerFile, file)
		}
		if s.Map.HalfExtentX != nil {
			cfg.Map.HalfExtentX = *s.Map.HalfExtentX
			set("map.halfExtentX", configulator.LayerFile, file)
		}
		if s.Map.HalfExtentY != nil {
			cfg.Map.HalfExtentY = *s.Map.HalfExtentY
			set("map.halfExtentY", configulator.LayerFile, file)
		}
	}
	if s.Poller != nil {
		if s.Poller.IntervalSeconds != nil {
			cfg.Poller.IntervalSeconds = *s.Poller.IntervalSeconds
			set("poller.intervalSeconds", configulator.LayerFile, file)
		}
		if s.Poller.IdleAfterSeconds != nil {
			cfg.Poller.IdleAfterSeconds = *s.Poller.IdleAfterSeconds
			set("poller.idleAfterSeconds", configulator.LayerFile, file)
		}
		if s.Poller.Health != nil {
			cfg.Poller.Health = *s.Poller.Health
			set("poller.health", configulator.LayerFile, file)
		}
		if s.Poller.HealthPerPoll != nil {
			cfg.Poller.HealthPerPoll = *s.Poller.HealthPerPoll
			set("poller.healthPerPoll", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "logLevel"); ok {
		cfg.LogLevel = LogLevel(v)
		set("logLevel", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); ok {
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = int(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "host"); ok {
		cfg.RCON.Host = v
		set("rcon.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.Port = int(p)
		set("rcon.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "password"); ok {
		cfg.RCON.Password = v
		set("rcon.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "timeoutSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.timeoutSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.TimeoutSeconds = int(p)
		set("rcon.timeoutSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "maxConcurrent"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.maxConcurrent",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.MaxConcurrent = int(p)
		set("rcon.maxConcurrent", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "map", "name"); ok {
		cfg.Map.Name = v
		set("map.name", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "map", "imagePath"); ok {
		cfg.Map.ImagePath = v
		set("map.imagePath", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "map", "halfExtentX"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentX",
				Source: n,
				Value:  v,
			}
		}
		cfg.Map.HalfExtentX = p
		set("map.halfExtentX", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "map", "halfExtentY"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentY",
				Source: n,
				Value:  v,
			}
		}
		cfg.Map.HalfExtentY = p
		set("map.halfExtentY", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "poller", "intervalSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.intervalSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Poller.IntervalSeconds = int(p)
		set("poller.intervalSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "poller", "idleAfterSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.idleAfterSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Poller.IdleAfterSeconds = int(p)
		set("poller.idleAfterSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "poller", "health"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.health",
				Source: n,
				Value:  v,
			}
		}
		cfg.Poller.Health = p
		set("poller.health", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "poller", "healthPerPoll"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.healthPerPoll",
				Source: n,
				Value:  v,
			}
		}
		cfg.Poller.HealthPerPoll = int(p)
		set("poller.healthPerPoll", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"logLevel",
		"http" + o.Separator + "bind",
		"http" + o.Separator + "port",
		"rcon" + o.Separator + "host",
		"rcon" + o.Separator + "port",
		"rcon" + o.Separator + "password",
		"rcon" + o.Separator + "timeoutSeconds",
		"rcon" + o.Separator + "maxConcurrent",
		"map" + o.Separator + "name",
		"map" + o.Separator + "imagePath",
		"map" + o.Separator + "halfExtentX",
		"map" + o.Separator + "halfExtentY",
		"poller" + o.Separator + "intervalSeconds",
		"poller" + o.Separator + "idleAfterSeconds",
		"poller" + o.Separator + "health",
		"poller" + o.Separator + "healthPerPoll",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log verbosity: debug, info, warn, or error")
	fs.String(names[1], "", "address to listen on; empty listens on all interfaces over both IPv4 and IPv6")
	fs.Var(impl.NewInt(8080), names[2], "TCP port to listen on")
	fs.String(names[3], "127.0.0.1", "hostname or IP of the Source RCON server")
	fs.Var(impl.NewInt(7779), names[4], "TCP port of the Source RCON server")
	fs.String(names[5], "", "RCON password (required)")
	fs.Var(impl.NewInt(5), names[6], "deadline in seconds covering a whole RCON exchange: connect, authenticate, command, response")
	fs.Var(impl.NewInt(4), names[7], "maximum RCON commands in flight at once")
	fs.String(names[8], "auto", "map the server runs: auto (detect over RCON), gondwa (aka island), panjura, riparia, or a custom name with both half extents set")
	fs.String(names[9], "", "map background image: a PNG file, or a directory holding <map>.png per map (required)")
	fs.Float64(names[10], 0.0, "world half extent on the X axis in Unreal units; 0 uses the named map's calibrated value")
	fs.Float64(names[11], 0.0, "world half extent on the Y axis in Unreal units; 0 uses the named map's calibrated value")
	fs.Var(impl.NewInt(10), names[12], "seconds between player polls while the map has viewers")
	fs.Var(impl.NewInt(30), names[13], "seconds without a browser request after which polling stops")
	fs.Bool(names[14], true, "sample player vitals (health and stamina) while the map has viewers")
	fs.Var(impl.NewInt(4), names[15], "players whose vitals are sampled per poll; vitals age between samples, positions do not")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "logLevel"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "logLevel",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("logLevel", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.host",
				Source: "--" + n,
			}
		}
		cfg.RCON.Host = v
		set("rcon.host", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.port",
				Source: "--" + n,
			}
		}
		cfg.RCON.Port = v
		set("rcon.port", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.password",
				Source: "--" + n,
			}
		}
		cfg.RCON.Password = v
		set("rcon.password", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "timeoutSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.timeoutSeconds",
				Source: "--" + n,
			}
		}
		cfg.RCON.TimeoutSeconds = v
		set("rcon.timeoutSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "maxConcurrent"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.maxConcurrent",
				Source: "--" + n,
			}
		}
		cfg.RCON.MaxConcurrent = v
		set("rcon.maxConcurrent", configulator.LayerCLI, "--"+n)
	}
	if n := "map" + o.Separator + "name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.name",
				Source: "--" + n,
			}
		}
		cfg.Map.Name = v
		set("map.name", configulator.LayerCLI, "--"+n)
	}
	if n := "map" + o.Separator + "imagePath"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.imagePath",
				Source: "--" + n,
			}
		}
		cfg.Map.ImagePath = v
		set("map.imagePath", configulator.LayerCLI, "--"+n)
	}
	if n := "map" + o.Separator + "halfExtentX"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentX",
				Source: "--" + n,
			}
		}
		cfg.Map.HalfExtentX = v
		set("map.halfExtentX", configulator.LayerCLI, "--"+n)
	}
	if n := "map" + o.Separator + "halfExtentY"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentY",
				Source: "--" + n,
			}
		}
		cfg.Map.HalfExtentY = v
		set("map.halfExtentY", configulator.LayerCLI, "--"+n)
	}
	if n := "poller" + o.Separator + "intervalSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.intervalSeconds",
				Source: "--" + n,
			}
		}
		cfg.Poller.IntervalSeconds = v
		set("poller.intervalSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "poller" + o.Separator + "idleAfterSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.idleAfterSeconds",
				Source: "--" + n,
			}
		}
		cfg.Poller.IdleAfterSeconds = v
		set("poller.idleAfterSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "poller" + o.Separator + "health"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.health",
				Source: "--" + n,
			}
		}
		cfg.Poller.Health = v
		set("poller.health", configulator.LayerCLI, "--"+n)
	}
	if n := "poller" + o.Separator + "healthPerPoll"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.healthPerPoll",
				Source: "--" + n,
			}
		}
		cfg.Poller.HealthPerPoll = v
		set("poller.healthPerPoll", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "logLevel":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("logLevel", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "rcon":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("rcon", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub rCONShadow
				if err := sub.decodeJSON(dec, "rcon"); err != nil {
					return err
				}
				s.RCON = &sub
			}
		case "map":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("map", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub mapShadow
				if err := sub.decodeJSON(dec, "map"); err != nil {
					return err
				}
				s.Map = &sub
			}
		case "poller":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("poller", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pollerShadow
				if err := sub.decodeJSON(dec, "poller"); err != nil {
					return err
				}
				s.Poller = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *rCONShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".password",
					Value: "(redacted)",
				}
			}
		case "timeoutSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".timeoutSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".timeoutSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.TimeoutSeconds = &num
			default:
				return configJSONError(path+".timeoutSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "maxConcurrent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".maxConcurrent", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".maxConcurrent", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.MaxConcurrent = &num
			default:
				return configJSONError(path+".maxConcurrent", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *mapShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Name = &str
			default:
				return configJSONError(path+".name", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "imagePath":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ImagePath = &str
			default:
				return configJSONError(path+".imagePath", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "halfExtentX":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".halfExtentX", v, err)
				}
				s.HalfExtentX = &num
			default:
				return configJSONError(path+".halfExtentX", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "halfExtentY":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".halfExtentY", v, err)
				}
				s.HalfExtentY = &num
			default:
				return configJSONError(path+".halfExtentY", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pollerShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "intervalSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".intervalSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".intervalSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.IntervalSeconds = &num
			default:
				return configJSONError(path+".intervalSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "idleAfterSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".idleAfterSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".idleAfterSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.IdleAfterSeconds = &num
			default:
				return configJSONError(path+".idleAfterSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "health":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Health = &b
			default:
				return configJSONError(path+".health", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "healthPerPoll":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".healthPerPoll", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".healthPerPoll", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.HealthPerPoll = &num
			default:
				return configJSONError(path+".healthPerPoll", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "logLevel = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "http.bind = %v\n", c.HTTP.Bind)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "rcon.host = %v\n", c.RCON.Host)
	fmt.Fprintf(&b, "rcon.port = %v\n", c.RCON.Port)
	b.WriteString("rcon.password = (redacted)\n")
	fmt.Fprintf(&b, "rcon.timeoutSeconds = %v\n", c.RCON.TimeoutSeconds)
	fmt.Fprintf(&b, "rcon.maxConcurrent = %v\n", c.RCON.MaxConcurrent)
	fmt.Fprintf(&b, "map.name = %v\n", c.Map.Name)
	fmt.Fprintf(&b, "map.imagePath = %v\n", c.Map.ImagePath)
	fmt.Fprintf(&b, "map.halfExtentX = %v\n", c.Map.HalfExtentX)
	fmt.Fprintf(&b, "map.halfExtentY = %v\n", c.Map.HalfExtentY)
	fmt.Fprintf(&b, "poller.intervalSeconds = %v\n", c.Poller.IntervalSeconds)
	fmt.Fprintf(&b, "poller.idleAfterSeconds = %v\n", c.Poller.IdleAfterSeconds)
	fmt.Fprintf(&b, "poller.health = %v\n", c.Poller.Health)
	fmt.Fprintf(&b, "poller.healthPerPoll = %v\n", c.Poller.HealthPerPoll)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
