// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"slices"
	"strconv"
	"strings"
)

type hTTPShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}
type rCONShadow struct {
	Host           *string `json:"host" toml:"host" yaml:"host"`
	Port           *int    `json:"port" toml:"port" yaml:"port"`
	Password       *string `json:"password" toml:"password" yaml:"password"`
	TimeoutSeconds *int    `json:"timeoutSeconds" toml:"timeoutSeconds" yaml:"timeoutSeconds"`
	MaxConcurrent  *int    `json:"maxConcurrent" toml:"maxConcurrent" yaml:"maxConcurrent"`
}
type mapShadow struct {
	Name        *string  `json:"name" toml:"name" yaml:"name"`
	ImagePath   *string  `json:"imagePath" toml:"imagePath" yaml:"imagePath"`
	HalfExtentX *float64 `json:"halfExtentX" toml:"halfExtentX" yaml:"halfExtentX"`
	HalfExtentY *float64 `json:"halfExtentY" toml:"halfExtentY" yaml:"halfExtentY"`
}
type pollerShadow struct {
	IntervalSeconds  *int  `json:"intervalSeconds" toml:"intervalSeconds" yaml:"intervalSeconds"`
	IdleAfterSeconds *int  `json:"idleAfterSeconds" toml:"idleAfterSeconds" yaml:"idleAfterSeconds"`
	Health           *bool `json:"health" toml:"health" yaml:"health"`
	HealthPerPoll    *int  `json:"healthPerPoll" toml:"healthPerPoll" yaml:"healthPerPoll"`
}
type configShadow struct {
	LogLevel *string       `json:"logLevel" toml:"logLevel" yaml:"logLevel"`
	HTTP     *hTTPShadow   `json:"http" toml:"http" yaml:"http"`
	RCON     *rCONShadow   `json:"rcon" toml:"rcon" yaml:"rcon"`
	Map      *mapShadow    `json:"map" toml:"map" yaml:"map"`
	Poller   *pollerShadow `json:"poller" toml:"poller" yaml:"poller"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("logLevel", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.RCON.Host = "127.0.0.1"
	set("rcon.host", configulator.LayerDefault, "default tag")
	cfg.RCON.Port = 7779
	set("rcon.port", configulator.LayerDefault, "default tag")
	cfg.RCON.TimeoutSeconds = 5
	set("rcon.timeoutSeconds", configulator.LayerDefault, "default tag")
	cfg.RCON.MaxConcurrent = 4
	set("rcon.maxConcurrent", configulator.LayerDefault, "default tag")
	cfg.Map.Name = "auto"
	set("map.name", configulator.LayerDefault, "default tag")
	cfg.Map.HalfExtentX = 0.0
	set("map.halfExtentX", configulator.LayerDefault, "default tag")
	cfg.Map.HalfExtentY = 0.0
	set("map.halfExtentY", configulator.LayerDefault, "default tag")
	cfg.Poller.IntervalSeconds = 10
	set("poller.intervalSeconds", configulator.LayerDefault, "default tag")
	cfg.Poller.IdleAfterSeconds = 30
	set("poller.idleAfterSeconds", configulator.LayerDefault, "default tag")
	cfg.Poller.Health = true
	set("poller.health", configulator.LayerDefault, "default tag")
	cfg.Poller.HealthPerPoll = 4
	set("poller.healthPerPoll", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}
func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("logLevel", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.RCON != nil {
		if s.RCON.Host != nil {
			cfg.RCON.Host = *s.RCON.Host
			set("rcon.host", configulator.LayerFile, file)
		}
		if s.RCON.Port != nil {
			cfg.RCON.Port = *s.RCON.Port
			set("rcon.port", configulator.LayerFile, file)
		}
		if s.RCON.Password != nil {
			cfg.RCON.Password = *s.RCON.Password
			set("rcon.password", configulator.LayerFile, file)
		}
		if s.RCON.TimeoutSeconds != nil {
			cfg.RCON.TimeoutSeconds = *s.RCON.TimeoutSeconds
			set("rcon.timeoutSeconds", configulator.LayerFile, file)
		}
		if s.RCON.MaxConcurrent != nil {
			cfg.RCON.MaxConcurrent = *s.RCON.MaxConcurrent
			set("rcon.maxConcurrent", configulator.LayerFile, file)
		}
	}
	if s.Map != nil {
		if s.Map.Name != nil {
			cfg.Map.Name = *s.Map.Name
			set("map.name", configulator.LayerFile, file)
		}
		if s.Map.ImagePath != nil {
			cfg.Map.ImagePath = *s.Map.ImagePath
			set("map.imagePath", configulator.LayerFile, file)
		}
		if s.Map.HalfExtentX != nil {
			cfg.Map.HalfExtentX = *s.Map.HalfExtentX
			set("map.halfExtentX", configulator.LayerFile, file)
		}
		if s.Map.HalfExtentY != nil {
			cfg.Map.HalfExtentY = *s.Map.HalfExtentY
			set("map.halfExtentY", configulator.LayerFile, file)
		}
	}
	if s.Poller != nil {
		if s.Poller.IntervalSeconds != nil {
			cfg.Poller.IntervalSeconds = *s.Poller.IntervalSeconds
			set("poller.intervalSeconds", configulator.LayerFile, file)
		}
		if s.Poller.IdleAfterSeconds != nil {
			cfg.Poller.IdleAfterSeconds = *s.Poller.IdleAfterSeconds
			set("poller.idleAfterSeconds", configulator.LayerFile, file)
		}
		if s.Poller.Health != nil {
			cfg.Poller.Health = *s.Poller.Health
			set("poller.health", configulator.LayerFile, file)
		}
		if s.Poller.HealthPerPoll != nil {
			cfg.Poller.HealthPerPoll = *s.Poller.HealthPerPoll
			set("poller.healthPerPoll", configulator.LayerFile, file)
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "logLevel"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("logLevel", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Bind = v
			set("http.bind", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = int(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "rcon", "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.RCON.Host = v
			set("rcon.host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "rcon", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "rcon.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.RCON.Port = int(p)
			set("rcon.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "rcon", "password"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.RCON.Password = v
			set("rcon.password", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "rcon", "timeoutSeconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "rcon.timeoutSeconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.RCON.TimeoutSeconds = int(p)
			set("rcon.timeoutSeconds", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "rcon", "maxConcurrent"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "rcon.maxConcurrent",
					Source: n,
					Value:  v,
				}
			}
			cfg.RCON.MaxConcurrent = int(p)
			set("rcon.maxConcurrent", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "map", "name"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Map.Name = v
			set("map.name", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "map", "imagePath"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Map.ImagePath = v
			set("map.imagePath", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "map", "halfExtentX"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "map.halfExtentX",
					Source: n,
					Value:  v,
				}
			}
			cfg.Map.HalfExtentX = p
			set("map.halfExtentX", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "map", "halfExtentY"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "map.halfExtentY",
					Source: n,
					Value:  v,
				}
			}
			cfg.Map.HalfExtentY = p
			set("map.halfExtentY", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "poller", "intervalSeconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "poller.intervalSeconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.Poller.IntervalSeconds = int(p)
			set("poller.intervalSeconds", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "poller", "idleAfterSeconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "poller.idleAfterSeconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.Poller.IdleAfterSeconds = int(p)
			set("poller.idleAfterSeconds", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "poller", "health"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "poller.health",
					Source: n,
					Value:  v,
				}
			}
			cfg.Poller.Health = p
			set("poller.health", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "poller", "healthPerPoll"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "poller.healthPerPoll",
					Source: n,
					Value:  v,
				}
			}
			cfg.Poller.HealthPerPoll = int(p)
			set("poller.healthPerPoll", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{strings.Join([]string{"logLevel"}, o.Separator), strings.Join([]string{"http", "bind"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"rcon", "host"}, o.Separator), strings.Join([]string{"rcon", "port"}, o.Separator), strings.Join([]string{"rcon", "password"}, o.Separator), strings.Join([]string{"rcon", "timeoutSeconds"}, o.Separator), strings.Join([]string{"rcon", "maxConcurrent"}, o.Separator), strings.Join([]string{"map", "name"}, o.Separator), strings.Join([]string{"map", "imagePath"}, o.Separator), strings.Join([]string{"map", "halfExtentX"}, o.Separator), strings.Join([]string{"map", "halfExtentY"}, o.Separator), strings.Join([]string{"poller", "intervalSeconds"}, o.Separator), strings.Join([]string{"poller", "idleAfterSeconds"}, o.Separator), strings.Join([]string{"poller", "health"}, o.Separator), strings.Join([]string{"poller", "healthPerPoll"}, o.Separator)}
	for i, name := range names {
		if fs.Lookup(name) != nil || slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log verbosity: debug, info, warn, or error")
	fs.String(names[1], "", "address to listen on; empty listens on all interfaces over both IPv4 and IPv6")
	fs.Int(names[2], 8080, "TCP port to listen on")
	fs.String(names[3], "127.0.0.1", "hostname or IP of the Source RCON server")
	fs.Int(names[4], 7779, "TCP port of the Source RCON server")
	fs.String(names[5], "", "RCON password (required)")
	fs.Int(names[6], 5, "deadline in seconds covering a whole RCON exchange: connect, authenticate, command, response")
	fs.Int(names[7], 4, "maximum RCON commands in flight at once")
	fs.String(names[8], "auto", "map the server runs: auto (detect over RCON), gondwa (aka island), panjura, riparia, or a custom name with both half extents set")
	fs.String(names[9], "", "map background image: a PNG file, or a directory holding <map>.png per map (required)")
	fs.Float64(names[10], 0.0, "world half extent on the X axis in Unreal units; 0 uses the named map's calibrated value")
	fs.Float64(names[11], 0.0, "world half extent on the Y axis in Unreal units; 0 uses the named map's calibrated value")
	fs.Int(names[12], 10, "seconds between player polls while the map has viewers")
	fs.Int(names[13], 30, "seconds without a browser request after which polling stops")
	fs.Bool(names[14], true, "sample player vitals (health and stamina) while the map has viewers")
	fs.Int(names[15], 4, "players whose vitals are sampled per poll; vitals age between samples, positions do not")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"logLevel"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "logLevel",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("logLevel", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "bind"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"rcon", "host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.host",
				Source: "--" + n,
			}
		}
		cfg.RCON.Host = v
		set("rcon.host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"rcon", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.port",
				Source: "--" + n,
			}
		}
		cfg.RCON.Port = v
		set("rcon.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"rcon", "password"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.password",
				Source: "--" + n,
			}
		}
		cfg.RCON.Password = v
		set("rcon.password", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"rcon", "timeoutSeconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.timeoutSeconds",
				Source: "--" + n,
			}
		}
		cfg.RCON.TimeoutSeconds = v
		set("rcon.timeoutSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"rcon", "maxConcurrent"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.maxConcurrent",
				Source: "--" + n,
			}
		}
		cfg.RCON.MaxConcurrent = v
		set("rcon.maxConcurrent", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"map", "name"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.name",
				Source: "--" + n,
			}
		}
		cfg.Map.Name = v
		set("map.name", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"map", "imagePath"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.imagePath",
				Source: "--" + n,
			}
		}
		cfg.Map.ImagePath = v
		set("map.imagePath", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"map", "halfExtentX"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentX",
				Source: "--" + n,
			}
		}
		cfg.Map.HalfExtentX = v
		set("map.halfExtentX", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"map", "halfExtentY"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "map.halfExtentY",
				Source: "--" + n,
			}
		}
		cfg.Map.HalfExtentY = v
		set("map.halfExtentY", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"poller", "intervalSeconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.intervalSeconds",
				Source: "--" + n,
			}
		}
		cfg.Poller.IntervalSeconds = v
		set("poller.intervalSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"poller", "idleAfterSeconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.idleAfterSeconds",
				Source: "--" + n,
			}
		}
		cfg.Poller.IdleAfterSeconds = v
		set("poller.idleAfterSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"poller", "health"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.health",
				Source: "--" + n,
			}
		}
		cfg.Poller.Health = v
		set("poller.health", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"poller", "healthPerPoll"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "poller.healthPerPoll",
				Source: "--" + n,
			}
		}
		cfg.Poller.HealthPerPoll = v
		set("poller.healthPerPoll", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "logLevel":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("logLevel: expected a string, got %v", v.Kind())
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "rcon":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub rCONShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.RCON = &sub
			}
		case "map":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub mapShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Map = &sub
			}
		case "poller":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub pollerShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Poller = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *hTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Bind = &str
			default:
				return fmt.Errorf("bind: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*hTTPShadow)(nil)

func (s *rCONShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Password = &str
			default:
				return fmt.Errorf("password: expected a string, got %v", v.Kind())
			}
		case "timeoutSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.TimeoutSeconds = &val
			default:
				return fmt.Errorf("timeoutSeconds: expected a number, got %v", v.Kind())
			}
		case "maxConcurrent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.MaxConcurrent = &val
			default:
				return fmt.Errorf("maxConcurrent: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*rCONShadow)(nil)

func (s *mapShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "imagePath":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.ImagePath = &str
			default:
				return fmt.Errorf("imagePath: expected a string, got %v", v.Kind())
			}
		case "halfExtentX":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.HalfExtentX = &val
			default:
				return fmt.Errorf("halfExtentX: expected a number, got %v", v.Kind())
			}
		case "halfExtentY":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.HalfExtentY = &val
			default:
				return fmt.Errorf("halfExtentY: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*mapShadow)(nil)

func (s *pollerShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "intervalSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.IntervalSeconds = &val
			default:
				return fmt.Errorf("intervalSeconds: expected a number, got %v", v.Kind())
			}
		case "idleAfterSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.IdleAfterSeconds = &val
			default:
				return fmt.Errorf("idleAfterSeconds: expected a number, got %v", v.Kind())
			}
		case "health":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Health = &b
			default:
				return fmt.Errorf("health: expected a bool, got %v", v.Kind())
			}
		case "healthPerPoll":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.HealthPerPoll = &val
			default:
				return fmt.Errorf("healthPerPoll: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*pollerShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("logLevel = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("http.bind = %v\n", c.HTTP.Bind))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	b.WriteString(fmt.Sprintf("rcon.host = %v\n", c.RCON.Host))
	b.WriteString(fmt.Sprintf("rcon.port = %v\n", c.RCON.Port))
	b.WriteString("rcon.password = (redacted)\n")
	b.WriteString(fmt.Sprintf("rcon.timeoutSeconds = %v\n", c.RCON.TimeoutSeconds))
	b.WriteString(fmt.Sprintf("rcon.maxConcurrent = %v\n", c.RCON.MaxConcurrent))
	b.WriteString(fmt.Sprintf("map.name = %v\n", c.Map.Name))
	b.WriteString(fmt.Sprintf("map.imagePath = %v\n", c.Map.ImagePath))
	b.WriteString(fmt.Sprintf("map.halfExtentX = %v\n", c.Map.HalfExtentX))
	b.WriteString(fmt.Sprintf("map.halfExtentY = %v\n", c.Map.HalfExtentY))
	b.WriteString(fmt.Sprintf("poller.intervalSeconds = %v\n", c.Poller.IntervalSeconds))
	b.WriteString(fmt.Sprintf("poller.idleAfterSeconds = %v\n", c.Poller.IdleAfterSeconds))
	b.WriteString(fmt.Sprintf("poller.health = %v\n", c.Poller.Health))
	b.WriteString(fmt.Sprintf("poller.healthPerPoll = %v\n", c.Poller.HealthPerPoll))
	return b.String()
}
